### ISSUE TITLE
How does it work

### ISSUE THREAD

**Issue by 7wells** [0ADMods/no-blood-and-gore-mod#1]
Hey Stan, would you mind briefly explaining how this mod works? Does your code overwrite existing files of 0 A.D. or is it more complex? Does your mod need to be adjusted with every new version of 0 A.D. (not only to show compatibility with the then-current-version, but also for technical reasons)? Thanks for your time helping me to understand this a bit better. :heart:

**Comment by StanleySweet** [comment]
This code overwrite every single actor in the game that has blood, or a bloodied texture. 
It needs to be updated for every version, if we add new units/variants that are not overwritten. (Or just update the textures)

**Comment by 7wells** [comment]
Is there a way to "tag" the original actors in the main game to ease the modification? I.e. to be able to automatically find the right files to modify them?

**Comment by StanleySweet** [comment]
Not that I know of. Other than grep

Stanislas Dolcini
________________________________

**Comment by 7wells** [comment]
Thank you!
